name: Deploy latest Docker image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t joshwatley/simple-site-tracker:latest .
          docker push joshwatley/simple-site-tracker:latest

      - name: Deploy latest Docker image
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: simple-site-tracker
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          # images: '[{"name": "simple-site-tracker","image":{"registry_type": "DOCKER_HUB","registry": "joshwatley","repository": "simple-site-tracker","tag": "latest"}}]'

